// Automatically generated by MockGen. DO NOT EDIT!
// Source: opener/engine/aws/client/ec2.go

package mock_client

import (
	ec2 "github.com/aws/aws-sdk-go/service/ec2"
	gomock "github.com/golang/mock/gomock"
)

// Mock of Ec2Client interface
type MockEc2Client struct {
	ctrl     *gomock.Controller
	recorder *_MockEc2ClientRecorder
}

// Recorder for MockEc2Client (not exported)
type _MockEc2ClientRecorder struct {
	mock *MockEc2Client
}

func NewMockEc2Client(ctrl *gomock.Controller) *MockEc2Client {
	mock := &MockEc2Client{ctrl: ctrl}
	mock.recorder = &_MockEc2ClientRecorder{mock}
	return mock
}

func (_m *MockEc2Client) EXPECT() *_MockEc2ClientRecorder {
	return _m.recorder
}

func (_m *MockEc2Client) DescribeInstancesByID(ids []string) []*ec2.Instance {
	ret := _m.ctrl.Call(_m, "DescribeInstancesByID", ids)
	ret0, _ := ret[0].([]*ec2.Instance)
	return ret0
}

func (_mr *_MockEc2ClientRecorder) DescribeInstancesByID(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DescribeInstancesByID", arg0)
}
